# Generated by Django 4.2.2 on 2023-09-19 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField(max_length=50)),
                ('main_photo', models.ImageField(upload_to='static/media/img/categories/')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('main_photo', models.ImageField(upload_to='static/media/img/<django.db.models.fields.related.ForeignKey>/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table_comment': 'Продукция',
                'ordering': ['category', 'size'],
                'indexes': [models.Index(fields=['category', 'size'], name='products_pr_categor_9e1fdb_idx')],
            },
        ),
    ]
